name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: aneesh123123/autoincrement  # Must match exactly your Docker Hub repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Verify Docker Hub permissions
        run: |
          echo "Testing Docker Hub access..."
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "'"${{ secrets.DOCKER_HUB_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_HUB_TOKEN }}"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          curl -s -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/" \
            | jq .

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.0.5
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_VERSION=1.0.5
